
export const BUSINESS_CATEGORIES = [
  "Accounting Services",
  "Architects",
  "Automobile Repair Shop",
  "Ayurvedic Clinic",
  "Bakery",
  "Bank",
  "Banquet Hall",
  "Beauty Parlour",
  "Book Store",
  "Boutique",
  "Builders & Developers",
  "CA (Chartered Accountant)",
  "Cafe",
  "Car Dealer",
  "Car Rental",
  "Catering Services",
  "Civil Contractors",
  "Cleaning Services",
  "Clothing Store",
  "Coaching Institute",
  "Computer Repair",
  "Courier Services",
  "Dance Class",
  "Dental Clinic",
  "Diagnostic Centre",
  "Digital Marketing Agency",
  "Doctors",
  "Driving School",
  "Dry Cleaners",
  "Electrician",
  "Electronics Store",
  "Event Management",
  "Eye Hospital",
  "Fashion Designer",
  "Financial Consultant",
  "Fitness Centre",
  "Florist",
  "Footwear Store",
  "Furniture Showroom",
  "Gift Shop",
  "Graphic Designer",
  "Grocery Store",
  "Gym",
  "Hardware Store",
  "Home Appliances Repair",
  "Homeopathy Clinic",
  "Hospital",
  "Hotel",
  "Ice Cream Parlour",
  "Immigration Consultant",
  "Industrial Equipment",
  "Insurance Agency",
  "Interior Designer",
  "Internet Service Provider",
  "Investment Firm",
  "IT Company",
  "Jewelry Showroom",
  "Laboratory",
  "Laundry Services",
  "Law Firm",
  "Lawyers",
  "Library",
  "Logistics Company",
  "Manufacturing Unit",
  "Marriage Bureau",
  "Mobile Shop",
  "Music Academy",
  "Nursery (Plants)",
  "Nursing Home",
  "Optician",
  "Orthopedic Clinic",
  "Packers and Movers",
  "Paint Shop",
  "Pathology Lab",
  "Pediatrician",
  "Pest Control",
  "Pet Shop",
  "Pharmacy",
  "Photographer",
  "Physiotherapy Clinic",
  "Plumber",
  "Printing Press",
  "Property Dealer",
  "Real Estate Agency",
  "Recruitment Agency",
  "Resort",
  "Restaurant",
  "RO Water Purifier Repair",
  "School",
  "Security Services",
  "Share Broker",
  "Skin Specialist",
  "Software Development",
  "Spa & Wellness",
  "Sports Goods Store",
  "Stationary Shop",
  "Sweet Shop",
  "Tailor",
  "Taxi Service",
  "Textile Industry",
  "Tiles & Sanitaryware",
  "Tour and Travel Agency",
  "Toy Store",
  "Training Centre",
  "Transport Services",
  "UPSC Coaching",
  "Veterinary Doctor",
  "Water Supplier",
  "Web Design Agency",
  "Wedding Planner",
  "Wholesale Cloth Market",
  "Wholesale Cosmetics",
  "Wholesale Electronics",
  "Wholesale FMCG",
  "Wholesale Fruit & Vegetable",
  "Wholesale Furniture",
  "Wholesale Grains",
  "Wholesale Grocery (Kirana)",
  "Wholesale Hardware",
  "Wholesale Jewelry",
  "Wholesale Medicine (Pharma)",
  "Wholesale Mobile Accessories",
  "Wholesale Plastic Goods",
  "Wholesale Saree",
  "Wholesale Stationery",
  "Wholesale Tiles",
  "Wholesale Toys",
  "Yoga Center"
];

export const MOCK_EMAILS = [
  "info@", "contact@", "hello@", "support@", "admin@"
];

export const STORAGE_KEYS = {
  HISTORY: 'leadgen_history',
  SETTINGS: 'leadgen_settings'
};

// Cleaned list of unique cities from the provided data
export const INDIA_CITIES = [
  "Port Blair", "Achanta", "Adoni", "Allur", "Amadalavalasa", "Amalapuram", "Anakapalle", "Anantapur", 
  "Annavaram", "Araku", "Atmakur", "Attilli", "Badvel", "Bapatla", "Bhimavaram", "Bobbili", "Chittoor", 
  "Dharmavaram", "Eluru", "Guntur", "Hindupur", "Kakinada", "Kurnool", "Machilipatnam", "Nellore", 
  "Ongole", "Rajahmundry", "Srikakulam", "Tirupati", "Vijayawada", "Visakhapatnam", "Vizianagaram", 
  "Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Guwahati", "Dibrugarh", "Silchar", "Jorhat", 
  "Nagaon", "Tinsukia", "Tezpur", "Bongaigaon", "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", 
  "Darbhanga", "Arrah", "Begusarai", "Katihar", "Munger", "Chandigarh", "Raipur", "Bilaspur", "Durg", 
  "Bhilai", "Korba", "Rajnandgaon", "Jagdalpur", "Ambikapur", "Silvassa", "Daman", "Diu", "New Delhi", 
  "Delhi", "Panaji", "Margao", "Vasco Da Gama", "Mapusa", "Ahmedabad", "Surat", "Vadodara", "Rajkot", 
  "Bhavnagar", "Jamnagar", "Junagadh", "Gandhinagar", "Gandhidham", "Anand", "Navsari", "Morbi", "Nadiad", 
  "Bharuch", "Porbandar", "Gurgaon", "Faridabad", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", 
  "Karnal", "Sonipat", "Panchkula", "Shimla", "Dharmsala", "Solan", "Mandi", "Baddi", "Hamirpur", "Srinagar", 
  "Jammu", "Anantnag", "Baramula", "Kathua", "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro Steel City", 
  "Hazaribagh", "Deoghar", "Bengaluru", "Mysore", "Hubli", "Dharwad", "Mangalore", "Belgaum", "Gulbarga", 
  "Davanagere", "Bellary", "Shimoga", "Tumkur", "Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", 
  "Thrissur", "Alappuzha", "Palakkad", "Kottayam", "Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", 
  "Sagar", "Dewas", "Satna", "Ratlam", "Rewa", "Mumbai", "Pune", "Nagpur", "Thane", "Pimpri Chinchwad", 
  "Nashik", "Kalyan-Dombivli", "Vasai-Virar", "Aurangabad", "Navi Mumbai", "Solapur", "Mira-Bhayandar", 
  "Bhiwandi", "Amravati", "Nanded", "Kolhapur", "Imphal", "Shillong", "Aizawl", "Kohima", "Dimapur", 
  "Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Pondicherry", "Amritsar", 
  "Ludhiana", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Jaipur", "Jodhpur", "Kota", "Bikaner", 
  "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Gangtok", "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", 
  "Salem", "Tirunelveli", "Ambattur", "Tiruppur", "Erode", "Vellore", "Hyderabad", "Warangal", "Nizamabad", 
  "Karimnagar", "Ramagundam", "Khammam", "Mahbubnagar", "Agartala", "Lucknow", "Kanpur", "Ghaziabad", 
  "Agra", "Meerut", "Varanasi", "Prayagraj", "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", 
  "Noida", "Greater Noida", "Firozabad", "Jhansi", "Muzaffarnagar", "Mathura", "Ayodhya", "Dehradun", 
  "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Kashipur", "Kolkata", "Howrah", "Asansol", "Siliguri", 
  "Durgapur", "Bardhaman", "Malda", "Baharampur", "Habra", "Kharagpur", "Shantipur"
].sort();
