
import { BusinessLead } from "../types";

export function exportToCSV(leads: BusinessLead[]) {
  const headers = ["Serial No", "Business Name", "Rating", "Reviews", "Email", "Phone", "Website", "Maps Link", "Address", "Distance (km)", "Owner Name", "Source", "Last Updated"];
  const rows = leads.map((lead, index) => [
    index + 1,
    `"${lead.name.replace(/"/g, '""')}"`,
    lead.rating || "N/A",
    lead.userRatingsTotal || 0,
    lead.email || "N/A",
    lead.phone || "N/A",
    lead.website || "N/A",
    lead.mapsUrl || "N/A",
    `"${lead.address.replace(/"/g, '""')}"`,
    lead.distance?.toFixed(2) || "N/A",
    lead.owner || "N/A",
    lead.source,
    lead.lastUpdated
  ]);

  const csvContent = [headers.join(","), ...rows.map(e => e.join(","))].join("\n");
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `business_leads_${new Date().getTime()}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToPDF(leads: BusinessLead[], categories: string[]) {
  const { jsPDF } = (window as any).jspdf;
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  // Title and Header
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Indigo-600
  doc.text('Business Leads Report', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by EasyLead | Total Leads: ${leads.length}`, 14, 28);
  
  // Display Business Categories
  doc.setFont("helvetica", "bold");
  doc.setTextColor(51, 65, 85); // Slate-700
  const categoryText = categories.length > 0 ? categories.join(", ") : "All Categories";
  doc.text(`Categories: ${categoryText}`, 14, 34);
  
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Date: ${new Date().toLocaleString()}`, 14, 40);

  const tableColumn = ["No.", "Business Name", "Rating", "Reviews", "Phone", "Email", "Website", "Google Maps", "Address"];
  const tableRows = leads.map((lead, index) => [
    index + 1,
    lead.name,
    lead.rating ? lead.rating.toFixed(1) : 'N/A',
    lead.userRatingsTotal || 0,
    lead.phone || 'N/A',
    lead.email || 'N/A',
    lead.website ? 'Visit Site' : 'N/A',
    lead.mapsUrl ? 'View Map' : 'N/A',
    lead.address
  ]);

  (doc as any).autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 46,
    theme: 'striped',
    headStyles: { 
      fillColor: [79, 70, 229],
      fontSize: 10,
      halign: 'center'
    },
    bodyStyles: { 
      fontSize: 8,
      valign: 'middle'
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 35, fontStyle: 'bold' },
      2: { cellWidth: 15, halign: 'center' },
      3: { cellWidth: 15, halign: 'center' },
      4: { cellWidth: 30 },
      5: { cellWidth: 30 },
      6: { cellWidth: 15, halign: 'center', textColor: [79, 70, 229] },
      7: { cellWidth: 20, halign: 'center', textColor: [79, 70, 229] },
      8: { cellWidth: 'auto' }
    },
    margin: { top: 46 },
    didDrawCell: (data: any) => {
      const lead = leads[data.row.index];
      if (data.section === 'body' && lead) {
        // Website Link Column (index 6)
        if (data.column.index === 6 && lead.website) {
          const url = lead.website.startsWith('http') ? lead.website : `https://${lead.website}`;
          doc.link(data.cell.x, data.cell.y, data.cell.width, data.cell.height, { url });
        }
        // Google Maps Link Column (index 7)
        if (data.column.index === 7 && lead.mapsUrl) {
          doc.link(data.cell.x, data.cell.y, data.cell.width, data.cell.height, { url: lead.mapsUrl });
        }
      }
    }
  });

  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
  }

  doc.save(`Leads_Report_${Date.now()}.pdf`);
}

export function copyToClipboard(leads: BusinessLead[]) {
  const text = leads.map(l => `${l.name}\t${l.rating || 'N/A'}\t${l.userRatingsTotal || 0}\t${l.email || 'N/A'}\t${l.phone || 'N/A'}\t${l.website || 'N/A'}\t${l.mapsUrl || 'N/A'}`).join("\n");
  navigator.clipboard.writeText(text);
  alert("Lead information copied to clipboard!");
}
